repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: "v5.3.1"
    hooks:
      - id: ansible-lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
